CMS-HGCAL/reco-prodtools

templates/partGun_GSD_template.py
templates/partGun_NTUP_template.py
templates/partGun_RECO_template.py

There are some important changes in this PR:
1. the `layerClusterPtThreshold` for the ntupliser is set to -1 to dump all layer clusters to the ntuple
1. clustering is rerun by default when running the ntupliser (using default settings) - it probably makes sense to have a flag for that later (volunteers?)
1. the geometry is updated to _D13_, which corresponds to v8 of HGCal
The latter change is needed to be able to run on the corresponding RelVals. Mind that using inconsistent geometries will lead to wrong results, i.e. re-running the clustering on a sample that has been produced with D4 will work, but will give wrong clusters and RecHits etc.

update config templates to D13

---

README.md
SubmitHGCalPGun.py
templates/partGun_GSD_template.py

Can be used to generate quarks or gluons to produce jets. Adds option `--gunMode`
which can be set to `default` or `pythia8`. Default behaviour of SubmitHGCalPGun.py
is unchanged.

Add option to use pythia8 particle gun

---

SubmitHGCalPGun.py
templates/partGun_GSD_template.py
templates/partGun_RECO_template.py

- add option for custom eta range,
- adapt config templates to run with 93X,
- adapt to change for EOS client when running on batch.

Add eta option and adapt to 93X/EOS changes

---

README.md
templates/python/produceSkeletons_D23_VtxSmearedHLLHC_noPU.sh
templates/python/produceSkeletons_D28_VtxSmearedHLLHC_noPU.sh
templates/python/produceSkeletons_D30_VtxSmearedHLLHC_noPU.sh

These have been created using `CMSSW_10_3_0_pre1` following instructions in https://indico.cern.ch/event/748252/contributions/3100080/attachments/1698943/2735337/hgcal_software_status_aug_8_2018.pdf

Add D28 and D30 fragment generation scripts

---

SubmitFileGSD.sh
SubmitHGCalPGun.py
submitNextStep.sh

HTCondor support for batch jobs is added. A practical guide is here [1]. There are a lot more features than 
LSF, however a practical difference is that a submission file should be specified. For this reason 
apart from the usual (std,cfg) directories a new directory (jobs) is created where the relevant .sub files 
are placed. In [2] I also put some useful info although we should educate ourselves better with this new tool. 
[1] http://batchdocs.web.cern.ch/batchdocs/local/lsfmigratepractical.html
[2] 
Queues
------
espresso     = 20 minutes
microcentury = 1 hour
longlunch    = 2 hours
workday      = 8 hours
tomorrow     = 1 day
testmatch    = 3 days
nextweek     = 1 week
Commands
--------
Removal/kill: condor_rm $USER
monitor like busers/bjobs: condor_q
like bpeek: condor_tail -f -stderr …

Migration to condor

---

SubmitHGCalPGun.py

@apsallid - I only realised this when I ran a more complicated job and my jobs were all failing. The default queue is "espresso" and there's no check for correct `JobFlavour` in HTCondor.

JobFlavour needs quotation marks

---

README.md
SubmitFileGSD.sh
SubmitHGCalPGun.py
templates/partGun_RECO_template.py

An option is added (`--keepDQMfile`) so that, if used, at the RECO step the DQM file will also be stored locally or in eos in a separate folder.

Store the dqm file

---

README.md
SubmitHGCalPGun.py
templates/partGun_GSD_template.py

In the PR [#26531](https://github.com/cms-sw/cmssw/pull/26531) the CloseByParticleGun was updated and starting from CMSSW_10_6_0 the `closeby` will crash. We update the code and the README file to synchronize with the latest CMSSW version. 
In order to explain the different options of the `closeby` gun this is an example command: 
`python SubmitHGCalPGun.py --datTier GSD --nevts 10 --evtsperjob 2 --queue tomorrow --partID 22,11,13 --nPart 1 --thresholdMin 60 --thresholdMax 60 --etaMin 1.4 --etaMax 3.0 --zMin 429.99 --zMax 430.01 --rMin 179.99 --rMax 180.01 --pointing --randomShoot --nRandomPart 10 --gunType E --gunMode closeby --eosArea /eos/cms/store/user/apsallid/HGCal --tag ${USER}_PDGId22_nPart1_E60_Scint_R180_Z430`
The new options `--randomShoot --nRandomPart 10` tells the gun to …

Updating the closeby gun

---

templates/partGun_NTUP_template.py

As of https://github.com/cms-sw/cmssw/commit/9be5bf9c60ce6390f3c1cf172412e228f65d1c64 , dEdX is a `PSet` with a member `weights`. This PR only contains a trivial change to reflect this in the NTUP template.

Fix usage of dEdX weights.

---

README.md
templates/python/produceSkeletons_D41_NoSmear_PU_AVE_200_BX_25ns.sh
templates/python/produceSkeletons_D41_NoSmear_noPU.sh
templates/python/produceSkeletons_D41_VtxSmearedHLLHC_noPU.sh

This PR updates the scripts that create the configuration templates in https://github.com/CMS-HGCAL/reco-prodtools/tree/master/templates/python to use the new geometry naming `2023` → `2026`. I tested this by running the GSD, RECO and NTUP steps.
Also, I moved all `cmsDriver.py` options to separate lines so that comparisons between them become a little more convenient in the future. I updated the README accordingly.
When merged, this fixes #68.

Update to geometry 2026.

---

README.md
templates/python/inject_ticl.sh
templates/python/produceSkeletons_D41_NoSmear_PU_AVE_200_BX_25ns.sh
templates/python/produceSkeletons_D41_NoSmear_noPU.sh
templates/python/produceSkeletons_D41_VtxSmearedHLLHC_noPU.sh

This PR adds the HGCal reconstruction performed in the TICL framework into the generated RECO fragment.
The injected lines are taken from the [HGCal docs](http://hgcal.web.cern.ch/hgcal/Reconstruction/TICL/).
I used a separate script to do the injection to keep redundancy low.

Inject ticl into the RECO fragment.

---

README.md
SubmitHGCalPGun.py

Apparently nobody ever wanted to shoot gluons into the HGCal, which is now fixed.
Also mentioned that the Pythia8 gun can be pT or energy. More details had already been added as part of #66.
Resolves #72 (unless anyone thinks we need more details/examples)

Extend Pythia8 gun description

---

.gitignore
SubmitHGCalPGun.py

This PR disentangles the SubmitHGCalPGun.py script from the contained option parser so that the mechanism to build GSD config files can be used externally, such as by the https://github.com/CMS-HGCAL/hgcalsim tool.
Also, this PR contains some cleanup regarding the treatment of requested particle ids.

Allow functionality of SubmitHGCalPGun.py to be used externally

---

SubmitHGCalPGun.py
templates/partGun_GSD_template.py

- Set upper threshold to lower threshold already when parsing options if upper one not provided so that the output file name does not contain `-1.0` as upper threshold but rather the actual threshold applied
- Streamline file naming and parsing for subsequent jobs: Make regex more robust and capable of handling physproc
closes #77

Output naming

---

templates/partGun_GSD_template.py

@apsallid pointed out that the phi ranges are not the same in the GSD template w.r.t. the ones in CMSSW:
- https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/CE_E_Front_120um_cfi.py
- https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/CE_E_Front_200um_cfi.py
- https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/CE_E_Front_300um_cfi.py
- https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/CE_H_Coarse_300um_cfi.py
- https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/CE_H_Coarse_Scint_cfi.py
- https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/CE_H_Fine_120um_cfi.py
- https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/CE_H_Fine_2 …

Align phi ranges in CloseByParticleGunProducer with those in CMSSW

---

README.md

This PR adds a small yet important note to the pileup scenario to express that a valid voms proxy is required to run the GSD step.
See #79 .

Add note on valid voms proxy for pilup scenario.

---

README.md
SubmitHGCalPGun.py

The `--tag` option has erroneously been ignored so far for NTUP and RECO steps, preventing the use of output directories different from the input directory (in case of non-RelVal jobs). This PR fixes this and also corrects the README.

Fix use of tag option in RECO and NTUP steps

---

README.md
templates/partGun_NTUP_template.py
templates/python/inject_nose.sh
templates/python/produceSkeletons_D44Nose_NoSmear_PU_AVE_200_BX_25ns.sh

Added HF+Nose skeleton.
See https://github.com/CMS-HGCAL/reco-ntuples/pull/81

Added HF+Nose option

---

README.md
SubmitFileGSD.sh
SubmitHGCalPGun.py

This enables the possibility of running the 3 steps together in one single submission by specifying the --datTier ALL option.

Allow for ALL steps to be ran in one submission.

---

README.md
SubmitHGCalPGun.py

By default, the gun is pointing to (0,0,0) and the flag is set to true, so now by calling the flag `--nopointing` and setting the `pointing` bool to false, particles are produced in parallel to the beampipe and there is no ambiguity in its meaning.

Replace `pointing` option by `nopointing` to remove ambiguity in its meaning
